name: Log Group

on:
  push:
    branches:
      - main

jobs:
  log_group:
    runs-on: ubuntu-latest
    steps:
      - name: Créer un groupe de log
        run: |
          echo "::group::ecole-it"
          echo "hello, ecole-it"
          echo "::endgroup::"
      - name: Afficher un message en dehors du groupe
        run: echo "ceci n'est pas dans le groupe."
